### ISSUE TITLE
Can't use string ("") as a HASH ref while "strict refs" in use at /usr/local/share/perl5/CGI/Auth/Basic.pm line 314.

### ISSUE THREAD

**Issue by nerfur** [burak/CPAN-CGI-Auth-Basic#1]
https://rt.cpan.org/Public/Bug/Display.html?id=100882
# !/usr/bin/perl -w

use strict; 
use warnings; 
use CGI::Auth::Basic; 
CGI::Auth::Basic->new( 
cgi_object => 'AUTOLOAD_CGI', 
# file => './password.txt',

password => 'hash', 
)->check_user; 
my $pok = print "Content-type: text/html\n\n" 
. 'You can use this program. ' 
. 'Now anything that this program does is accessible! :)' ; 

This code produces: 

Can't use string ("") as a HASH ref while "strict refs" in use at /usr/local/share/perl5/CGI/Auth/Basic.pm line 314.

**Comment by burak** [comment]
Seems to be fixed long ago.
